### ISSUE TITLE
Full move clock after white move is off by 1

### ISSUE THREAD

**Issue by dkappe** [capicue/pgn#6]
After 1. e4, the fen should be rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1

Instead it is rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 0

**Comment by r11runner** [comment]
I've already submitted a pull request to fix this issue:
https://github.com/capicue/pgn/pull/5

**Comment by dkappe** [comment]
Thanks.

**Comment by capicue** [comment]
Sorry about the negligence! Merged & released a new version.

https://rubygems.org/gems/pgn/versions/0.1.0
