### ISSUE TITLE
Does pgn parse games w/ timestamps?

### ISSUE THREAD

**Issue by Nixonite** [capicue/pgn#7]
Hi,

Is there a hidden method somewhere not mentioned that parses a PGN with timestamps included? I noticed that the method in the README doesn't work for it, and the example doesn't include timestamps. 

I could always just remove the timestamps manually with regex before parsing, but I'm wondering if the library might have an option for it already.

Thanks for your time. Cool library btw. There is no similarly simple and powerful python equivalent.

**Comment by tobiasvl** [comment]
Hey, fork maintainer chiming in!

Timestamps aren't a part of the PGN standard, are they? I thought timestamps were usually just special annotations (which the parser should read and throw away). What's the format?

**Comment by Nixonite** [comment]
Yes they are simply special annotations i.e. enclosed in curly braces {}

I did however run into trouble with using this program with timestamps (didn't parse), but it seemed to work fine after I regex'd out the timestamps. How do you parse a PGN w/ annotations?

**Comment by tobiasvl** [comment]
Yeah, I basically just regex them out myself in my fork: https://github.com/tobiasvl/pgn

**Comment by capicue** [comment]
Merged & released. https://rubygems.org/gems/pgn/versions/0.1.0

Thanks again to @tobiasvl for the fixes!
