### ISSUE TITLE
Error: Unmatched input

### ISSUE THREAD

**Issue by rubdos** [capicue/pgn#9]
PGN doesn't seem to like this file:

(which I lost, because I did a retarded Bishop sacrifice, iirc)

```
[Event "---"]
[Site "---"]
[Date "---"]
[Round "---"]
[White "Ruben De Smet"]
[Black "---"]
[Result "*"]
[ECO "D52"]
[WhiteElo ""]
[BlackElo ""]
[TimeControl ""]
[Time ""]
[PlyCount "60"]
[EventDate ""]
[Annotator ""]

1. d4 e6 2. c4 d5 3. Nc3 c6 4. Nf3 Nf6 5. Bg5 Nbd7 6. e3 Qa5 7. a3 (7. cxd5
Nxd5 8. Rc1 {Analyzer's primary variation: 8... Bb4 9. Qd2 e5 10. e4 Nxc3 11.
bxc3 Ba3 12. Rb1 h6 13. Be3 O-O 14. Bc4 exd4 15. cxd4 Qxd2+ 16. Nxd2 a5 17. O-O
b5 18. Be2 Rd8 19. d5 cxd5 20. exd5 Nc5 21. Rxb5 Rxd5 {+0.30/21} }) 7... Ne4 8.
Rc1 Nxg5 9. Nxg5 dxc4 10. Bxc4 Qxg5 11. O-O Nf6 12. Qf3 Qg4 13. Qxg4 Nxg4 14.
Ne4 Be7 15. b4 O-O 16. Rce1 Nf6 17. Ng5 ({Better is} 17. Nxf6+ gxf6 {-4.08/31}
(17... Bxf6) (17... gxf6)) (17. Nxf6+) 17... h6 18. Nf3 Ne4 ({Treatening} 18...
-- 19. Ra1 b5 {-4.05/31}) ({Better is} 18... a5 19. Be2 {-4.55/31}) 19. Bd3 Ng5
({Treatening} 19... -- 20. Bxe4 a5 21. Rb1 axb4 22. axb4 Ra4 23. b5 c5 24. Bc2
Ra3 25. Rfc1 cxd4 26. Nxd4 Rd8 27. b6 Ra5 28. Be4 Rc5 29. f4 g5 30. g3 f5 31.
Bg2 Kf7 32. Bf3 g4 33. Bg2 Kf6 34. Ra1 Kf7 35. Rab1 {0.00/36}) ({Better is}
19... Nc3 20. Ra1 {-4.02/33}) 20. Ne5 Bd6 21. Nc4 Rd8 22. f4 Nh7 23. Na5 Bc7
24. Nb3 ({Better is} 24. Bc4 Nf6 25. Rb1 g5 26. g3 gxf4 27. gxf4 Kf8 28. Rfc1
Ng4 29. Rc3 Ke7 30. Rb2 Bb6 31. Nb3 Nf6 32. Rcc2 Rg8+ 33. Rg2 Rxg2+ 34. Kxg2 a5
35. bxa5 Bxa5 36. Nxa5 Rxa5 37. Rb3 b5 38. Be2 Ra4 39. Rc3 Bd7 40. Bf3
{-3.58/30}) 24... Nf6 25. e4 ({Better is} 25. Ra1 a5 26. Kf2 Ng4+ 27. Ke2 Nxh2
28. Rfc1 Bb6 29. Nc5 axb4 30. axb4 Rxa1 31. Rxa1 Ng4 32. b5 cxb5 33. Bxb5 Nf6
34. Ra8 Nd5 35. Ra3 Bc7 36. Nd3 g6 37. Bc4 Kg7 38. Kf3 h5 39. Ra1 b6 40. Kf2
Nf6 41. Ra7 Ng4+ 42. Ke2 Bd6 {-4.21/28}) 25... Bd7 26. e5 Nd5 27. f5 exf5 28.
Bxf5 ({Treatening} 28. -- Ne7 29. Bc2 Be6 30. Nc5 Rxd4 31. Nxe6 fxe6 32. Rd1
Rxd1 33. Rxd1 Nd5 34. Bb3 Bxe5 35. a4 Kf7 36. b5 c5 37. Kf2 Bxh2 38. Re1 Rd8
39. a5 Nf4 40. Rd1 Rxd1 41. Bxd1 c4 42. g3 Nd3+ 43. Kg2 {+5.66/25}) ({Better
is} 28. Nc5 Bb6 {-4.87/28}) 28... Bxf5 29. Rxf5 Bb6 ({Treatening} 29... -- 30.
Nc5 Bb6 31. Rff1 Re8 32. Rf2 f6 33. Rfe2 fxe5 34. Rxe5 Rxe5 35. Rxe5 a5 36.
bxa5 Bxa5 37. Nxb7 Bc3 38. Re4 Nf6 39. Re6 Bxd4+ 40. Kf1 Rxa3 41. Rxc6 Ng4 42.
Rc8+ Kh7 43. Ke2 Nxh2 44. Rc4 Bg1 45. Re4 Kg6 46. Nd6 Ra2+ 47. Kd3 Rxg2
{-4.52/25}) ({Better is} 29... a5 30. Nxa5 {-5.43/26}) 30. Ref1 ({Better is}
30. Rf3 a5 {-4.81/28}) 30... Ne3 *
```

(I censored black's name, the date and the tournament)

I'm still trying to figure out why; but I get this:

    Error:  Unmatched input "}) 7... Ne4 8.\nRc1 Nxg5 [SNIP]" on line 20

(I cut it at [SNIP], it just dumps the rest of the file)

To me, this looks like PGN doesn't like `pgn` files with variations halfway a move (move 7., in this case, first line. Long variation that lasts until line 20), but I'm not sure. I'm trying to read the parser spec atm. If I can fix it, I'll make a PR. Any help is appreciated though; reading a parser spec is not so easy :')

I'm trying to use this library to automatically get my chess games on my blog, using Jekyll!

This file was created by PyChess, which I use to enter my games.

**Comment by rubdos** [comment]
I found out what causes this; closing braces are disallowed in `:comment`s, but PyChess is using one. I'll try to make embedded matching braces work.

**Comment by rubdos** [comment]
> EDIT: actually, you can just allow the closing brace in :comment, can't you? The parser will crash anyhow if braces do not match. I'll put that in my merge request; if you disagree, I'll work out something more pleasant :)

Nope, you can't. It generates ambiguity in something like {comment} a3 {comment}. I'll make it smarter then.

**Comment by capicue** [comment]
Thanks so much for reporting this and working on it.

In looking over the code, I realized there's a big limitation with whittle. It doesn't allow for matching zero or more of a rule. The only way then to parse recursive structures is through regular expressions which weren't originally designed for that. The `\g<name>` syntax was introduced in Ruby 1.9.2, so this change will break things for people using an older version. I'm going to assume that there aren't that many holdouts and accept the change.

The only elegant way to fix it is a rewrite of the parsing stuff with a better library ([rsec](http://rsec.herokuapp.com/ref) looks nice), but this is a perfectly reasonable holdover until I get around to that.

Thanks again!
